# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.4"
manifest_format = "2.0"
project_hash = "600a48223906ad5dc045fd31af4ccd0cc182166b"

[[deps.ZedPlotPane]]
path = "."
uuid = "1a2e9a1c-d784-4d3f-8c27-9f27d983cc09"
version = "0.1.0"
